version: '3'
services:
  jpo_kafka_counter:
    build: .
    image: jpo_bsm_query:latest
    restart: always
    env_file:
      - .env
    logging:
      options:
        max-size: '10m'
        max-file: '5'
